package peyto.ide.core.service.types;

public enum SourceCodeType {

	MYBATIS_DAO,
	MYBATIS_TEST_DAO,
	MYBATIS_MAPPER,
	MYBATIS_DTO,
	
	SPRING_JPA_CODE,
	SPRING_JPA_TEST_CODE,
	SPRING_JPA_ENTITY,
	
	SPRING_REST_CODE,
	SPRING_REST_TEST_CODE,
	SPRING_REST_DATA,
	
	FLASK_REST_CODE,
	FLASK_REST_TEST_CODE,
	FLASK_REST_DATA,
	
	REACT_TS_REST,
	REACT_TS_TEST_REST,
	REACT_TS_TYPE
}